<head>
    <link rel="stylesheet" href="estilo/styleRodape.css">
</head>
<footer>
    <h3 class="info">E-mail: exemplo@exemplo.com <br>
    Local: Cidade Exemplo, Rua Exemplo, Nº Exemplo</h3>
    <a href="#">
        <img src="imagem/insta.png" height="60">
    </a>
    <a href="#">
        <img src="imagem/whats.png" height="90">
    </a>
    <a href="#">
        <img src="imagem/face.webp" height="90">
    </a>
</footer>